travis:
  secure:
    BINSTAR_TOKEN: lUkqewIZfgF5IxSHcNIbUPOWRgFqREw1dB0GnpNL6W4kAgtdxUjl3GI/4Vp91rbahoUqSaXE5FpSwiFeO7CoVe4g9Mw5y3RKYuUNT7q9kBg6yAgl00iKMONfatefba/GU1UGUxSvYNBhH7fjZ/0FTGeXTFz839fkb5YIIoavVpvYnJy07vl+apGa0fj+j38nmFytAy0p7QVYaLg34+P3gsCb/0KtZvJvvesQJnrgQit9bpfiMB4XNtU/v5yilNOmWf+C8XwvMyXHmK6jIW+Whp8ziDcxX03MUpHsBR8v1mgF1WLzGent9DAJ93QTNvXiVC6yZ5KsC4Xbwah8teyEGY3b+1NwU214QzCkT9SCibSb9eZadFDH2h0ftBmKkRWIR889jyA2TytrR2yYqICH1vWC0IhEnepcYrKRDp3JUVcIVGuJH4s43XkihWDOma9CBPe2UzL/rYDzQZK5JgR3DsA9JiFp+8GeLiGEWO+k5/A2Ae21N73LXSUHXRTEEd6ZBxqueosE/ygzFQ8BulvwHZvsBXaj7ZOzQ6kiewjmrp90iTDkXOymT1YVHchJfVZ8TsSzD+lpbr+io9gqvnOuCEUykOYnZyqlxnD+ZH7UFu7CBecB8Ys0mAXFSmqk25AfYnMli34nglrTtwV6hlWaUwqjwsW9gbYi7uh6+k3q36U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
